name: KikakuUtils
version: ${project.version}
main: net.kunmc.lab.kikakuutils.KikakuUtils
api-version: 1.15
authors: [ Nagatuki ]
description: 単発企画、攻城戦企画のための管理ツール
website: None

commands:
  kikaku:
    usage: Unknown command. Type "/kikaku help" for help. <- まだ実装してない
    description: 50 ninn kikaku utilities
    permission: kikakuutils
    aliases:
      - ku
  kikaku-internal-ask:
    usage: Kikaku Utilsプラグインの内部コマンドです。使わないでね。
    description: This is an internal command of Kikaku Util plugin.
    permission: kikakuutils.internal.ask

permissions:
  kikakuutils:
    default: op
  kikakuutils.rule.reject:
    description: KikakuUtilsのkuコマンドによる設定変更を拒否することができる権限
    default: op
  kikakuutils.internal.ask:
    description: KikakuUtils内部コマンド用権限
    default: true
